on:
  schedule:
  - cron: '*/30 * * * *'
  workflow_dispatch:

name: Create Release with SPT Integration

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      trigger_build: ${{ steps.check.outputs.trigger_build }}
    steps:
      - name: Get latest release tag
        id: get_release
        run: |
          latest_release=$(curl -s "https://api.github.com/repos/cocorico8/Fika-Server/tags" | jq -r '.[0].name')
          echo "Latest release: $latest_release"
          echo "LATEST_RELEASE=$latest_release" >> $GITHUB_ENV

      - name: Retrieve last release version
        run: |
          echo last_release=$(curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.PAT }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/cocorico8/Fika-Server/actions/variables/LAST_RELEASE | jq -r '.value')
          echo "Last release: $last_release"
          echo "LAST_RELEASE=$last_release" >> $GITHUB_ENV

      - name: Compare with last built release
        id: check
        run: |
          echo "Comparing LATEST_RELEASE: $LATEST_RELEASE vs LAST_RELEASE: $LAST_RELEASE"
          
          if [ "$LAST_RELEASE" != "$LATEST_RELEASE" ]; then
            curl -X PATCH -H "Authorization: token ${{ secrets.PAT }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/cocorico8/Fika-Server/actions/variables/LAST_RELEASE \
               -d "{\"value\":\"$LATEST_RELEASE\"}"
            echo "New release detected!"
            echo "trigger_build=true" >> $GITHUB_OUTPUT
          else
            echo "No new release found."
            echo "trigger_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-release
    if: ${{ needs.check-release.outputs.trigger_build == 'true' }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ,"windows-latest" ]
    permissions: write-all
    name: Create Release
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout FIKA-Server-Mod Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Read package.json
        id: read_package_json
        run: |
          echo "::set-output name=version::$(node -e 'console.log(require(`./package.json`).version)')"
          echo "::set-output name=sptVersion::$(node -e 'console.log(require(`./package.json`).sptVersion)')"
      - name: Build Release Package
        id: build
        shell: pwsh
        run: |
          ./.github/workflows/scripts/package_release_with_server.ps1 -Overwrite -FIKACoopVer ${{ steps.read_package_json.outputs.version }}
          echo "ZIP_NAME=$(Get-Content "$env:GITHUB_OUTPUT" | Select-String -Pattern "^ZIP_NAME=").Value.Split('=')[1]" >> $GITHUB_ENV
          echo "COMMIT_SHORT=$(Get-Content "$env:GITHUB_OUTPUT" | Select-String -Pattern "^CommitShort=").Value.Split('=')[1]" >> $GITHUB_ENV
          echo "SPT_VERSION=$(Get-Content "$env:GITHUB_OUTPUT" | Select-String -Pattern "^SPT_VERSION=").Value.Split('=')[1]" >> $GITHUB_ENV
      - name: Debug output variables
        run: |
          echo "SPT_VERSION: ${{ env.SPT_VERSION }}"
          echo "COMMIT_SHORT: ${{ env.COMMIT_SHORT }}"
          echo "ZIP_NAME: ${{ env.ZIP_NAME }}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.read_package_json.outputs.version }}
          name: FIKACoop-${{ steps.read_package_json.outputs.version }}-WithSPT-${{ env.SPT_VERSION }}-${{ env.COMMIT_SHORT }}
          files: |
            ${{ env.ZIP_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
